ユーザ登録機能の追加
kuniyoshi9244/backend_assignment pull request #1
Opened 2021-08-14 11:00 UTC by kuniyoshi9244

2021-08-20 09:27 UTC, fumiharun11 requested changes

2021-08-20 09:27 UTC, fumiharun11 commented on twitter/forms.py
> +class UserForm(forms.ModelForm):
Djangoには`UserCreationForm`という新規ユーザー作成用途のモデルフォームクラスが存在します。
今回ユーザーとして使用するクラスがDjango標準の`User`モデルなので、上記フォームクラスを利用することで`labels`のカスタマイズのみで済むかと思います。

また、ユーザー登録時はパスワードの再確認フォームが一般的に存在しているので、その観点でも上記フォームクラスの使用をお勧めします。
直接`ModelForm`クラスを継承してフォームを作成している理由があれば、このメッセージに対して返信をお願いします。

[参考](https://docs.djangoproject.com/ja/3.2/topics/auth/default/#django.contrib.auth.forms.UserCreationForm)

2021-08-20 09:27 UTC, fumiharun11 commented on twitter/views.py
> +        "AccountCreate":False,
こちらのフラグは何のために存在しますか？
template内でも使用していないと思うので確認です。

2021-08-20 09:27 UTC, fumiharun11 commented on twitter/views.py
> +class  AccountRegistration(TemplateView):
汎用ビュー`CreateView`を継承したViewを定義すると詳細な処理をDjango側に任せることが出来るので、複雑な処理が発生しない場合はお勧めです。

2021-08-20 09:27 UTC, fumiharun11 commented on twitter/views.py
> +            print(self.params["user_form"].errors)
こちらのprintはデバッグ用途で記述されているものですか？

2021-08-20 09:27 UTC, fumiharun11 commented on twitter/views.py
> +        self.params = {
ここで定義したインスタンス変数`self.params`を`get()`及び`post()`メソッドの処理でrender時のcontextに渡していますが、あえてインスタンス変数で渡している理由はありますか？
それぞれのメソッド内で`context`に渡すための辞書を定義する方針でも良いと思いました。

2021-08-20 09:27 UTC, fumiharun11 commented on twitter/views.py
> +        self.params["user_form"] = UserForm()
contextに渡す値を変更したいだけであれば`get()`メソッドではなく`get_context_data()`メソッドの使用をお勧めします。

2021-08-20 09:27 UTC, fumiharun11 commented on twitter/views.py
> +class  AccountRegistration(TemplateView):
`TemplateView`を使用する場合は、よりメリットを活かすために以下のdocsを参考にしてみてください。

参考: https://docs.djangoproject.com/en/3.2/ref/class-based-views/base/#django.views.generic.base.TemplateView

2021-08-24 05:45 UTC, kuniyoshi9244 commented on twitter/forms.py
> +class UserForm(forms.ModelForm):
ModelFormクラスを継承している理由は特にございません。
ユーザ登録用画面のフォームとして、UserCreationFormクラスを使用するように変更いたしました。

2021-08-24 05:48 UTC, kuniyoshi9244 commented on twitter/views.py
> +        "AccountCreate":False,
register.htmlの中で'登録成功!'の文字を出力可否の判定フラグとして使用していましたが、
一旦削除いたしました。

2021-08-24 05:49 UTC, kuniyoshi9244 commented on twitter/views.py
> +class  AccountRegistration(TemplateView):
CreateViewを継承したViewを使用する方針に変更いたしました。

2021-08-24 05:51 UTC, kuniyoshi9244 commented on twitter/views.py
> +            print(self.params["user_form"].errors)
デバッグ用です。
CreateViewを継承したViewを使用することとしたため、削除いたしました。

2021-08-24 05:52 UTC, kuniyoshi9244 commented on twitter/views.py
> +        self.params = {
CreateViewを継承したViewを使用し、form_classに'UserCreationForm'を設定したため、該当部分を削除いたしました。

2021-08-24 05:53 UTC, kuniyoshi9244 commented on twitter/views.py
> +        self.params["user_form"] = UserForm()
CreateViewを継承したViewを使用し、form_classに'UserCreationForm'を設定したため、該当部分を削除いたしました。

2021-08-30 05:40 UTC, fumiharun11 approved these changes
確認いたしました。
正常に動作していて良いと思います。

一点、今後`twitter`のように`python manage.py startapp [app_name]`でアプリケーションを生成する際、URLの名前空間に注意するようにしてください。
恐らく次回以降のPRのどこかで意識することになるので、参考ドキュメントを以下に添付いたします。
引き続き頑張りましょう！
https://docs.djangoproject.com/ja/3.2/topics/http/urls/#term-application-namespace

2021-08-30 05:48 UTC, merged