ツイート機能の追加
kuniyoshi9244/backend_assignment pull request #4
Opened 2021-09-05 11:43 UTC by kuniyoshi9244

ツイート機能を追加しました。

2021-09-09 05:24 UTC, fumiharun11 requested changes

2021-09-09 05:24 UTC, fumiharun11 commented on twitter/views.py
> +#    model = Tweet
こちらコメントアウトして残している理由はありますか？

2021-09-09 05:24 UTC, fumiharun11 commented on twitter/templates/twitter/home.html
> +    <span class="user_name">{{ tweet.user }}</span>
`tweet.user`についてViewの実装次第でN+1問題が発生します。
該当Viewにコメントを記載しているのでそちらの確認をお願いします。

2021-09-09 05:24 UTC, fumiharun11 commented on twitter/views.py
> +        """Return the last five published questions."""
こちらのコメント内容と実際に返しているQuerySetの内容が合っていないようにも見えるのですが、コメント内容が何を表しているか教えていただけますか？

2021-09-09 05:24 UTC, fumiharun11 commented on twitter/views.py
> +        return Tweet.objects.filter(user = self.request.user).order_by('-pub_date')
Template(twitter/home.html)内で`tweet.user`をループ処理内で参照していますが、こちらで返されるQuerySetのままではN+1問題が発生しているかと思います。
『Django N+1』などで検索し、対応をお願いします。

参考: https://docs.djangoproject.com/en/3.2/ref/models/querysets/#select-related

2021-09-09 14:31 UTC, kuniyoshi9244 commented on twitter/views.py
> +#    model = Tweet
消し忘れのため、削除いたしました。

2021-09-09 14:35 UTC, kuniyoshi9244 commented on twitter/templates/twitter/home.html
> +    <span class="user_name">{{ tweet.user }}</span>
N+1問題が発生しないように、HomeViewのquerysetを修正いたしました。

2021-09-09 14:46 UTC, kuniyoshi9244 commented on twitter/views.py
> +        return Tweet.objects.filter(user = self.request.user).order_by('-pub_date')
querysetを取得するチェーンにselect_related('user')を追加し、一回のクエリの発行でデータを取得できるように修正いたしました。

2021-09-09 14:47 UTC, kuniyoshi9244 commented on twitter/views.py
> +        """Return the last five published questions."""
不要なコメントのため削除いたしました。

2021-09-10 03:36 UTC, fumiharun11 approved these changes
LGTMです！

2021-09-10 03:36 UTC, merged